### PR TITLE
Add ndjson extension to mime types

### PR DESCRIPTION
**Pull request by RouatbiH**

### CODE REVIEW

**Comment by frankdejonge** [comment]
Your mime-type is added to a generated file, which will be overwritten when re-generated. Please add it to `FlysystemProvidedMimeTypeProvider` and provide links to authoritative sources that validate the mime-type's authenticity.

**Comment by RouatbiH** [comment]
@frankdejonge Done
Links: https://github.com/ndjson/ndjson-spec#33-mediatype-and-file-extensions

**Comment by frankdejonge** [comment]
@RouatbiH can you resolve the merge conflict?

**Comment by frankdejonge** [comment]
@RouatbiH never mind, fixed the conflict.

**Comment by frankdejonge** [comment]
released as 1.14.0

**Pull request merged**
